version: '3.8'

services:
  mcp-server:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mcp-collections-server:latest
    container_name: mcp-collections-server
    ports:
      - "80:80"
    environment:
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - OUTLOOK_USER_EMAIL=${OUTLOOK_USER_EMAIL}
      - COLLECTIONS_FOLDER_NAME=${COLLECTIONS_FOLDER_NAME:-Inbox}
      - API_ENDPOINT=${API_ENDPOINT}
      - API_KEY=${API_KEY}
      - WEBHOOK_ENABLED=${WEBHOOK_ENABLED:-true}
      - WEBHOOK_PORT=80
      - WEBHOOK_PUBLIC_URL=${WEBHOOK_PUBLIC_URL:-http://localhost}
      - WEBHOOK_CLIENT_STATE=${WEBHOOK_CLIENT_STATE}
      - LLM_WEBHOOK_URL=${LLM_WEBHOOK_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/temp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16