# WARNING: DO NOT COMMIT THIS FILE WITH REAL VALUES
# This is a template file. Create secrets using kubectl or a secrets management tool.

# Example secret creation command:
# kubectl create secret generic mcp-server-secret \
#   --from-literal=AZURE_CLIENT_ID='your-client-id' \
#   --from-literal=AZURE_CLIENT_SECRET='your-client-secret' \
#   --from-literal=AZURE_TENANT_ID='your-tenant-id' \
#   --from-literal=WEBHOOK_CLIENT_STATE='your-webhook-secret' \
#   --from-literal=API_KEY='your-api-key'

apiVersion: v1
kind: Secret
metadata:
  name: mcp-server-secret
type: Opaque
stringData:
  AZURE_CLIENT_ID: "REPLACE_ME"
  AZURE_CLIENT_SECRET: "REPLACE_ME"
  AZURE_TENANT_ID: "REPLACE_ME"
  WEBHOOK_CLIENT_STATE: "REPLACE_ME"
  API_KEY: "REPLACE_ME"